# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c329a52289340674da47e0c885caf6ef44e0e7cc223d36e0dd87108d06005ed64464d148bc6380e435761feadbc30d8b48db3706f0268e885c71210649fc3be0

test:
  secret_key_base: b27b7b55fa6af39b0f8cdad1c19181517544214a97de06e948f849adde6bbd48694e271620306652e9f57cd91eb8aaae0f5abebe7eb084c8bf043d1a2513e95e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
